#!/usr/bin/env ruby

require "active_support"
require "active_support/core_ext/numeric/bytes"
require "logger"
require "opensearch/audit"
require "opensearch/cli"

logger = Logger.new($stdout)
logger.level = Logger::WARN

options = {
  logger: logger,
  periodic: false,
  min_shard_size: 10.gigabytes,
  max_shard_size: 50.gigabytes
}

def parse_bytes(s)
  s.upcase =~ /\A(\d+)([KMGT])?B?\z/
  m = {
    nil => 1,
    "K" => 1.kilobyte,
    "M" => 1.megabyte,
    "G" => 1.gigabyte,
    "T" => 1.terabyte
  }
  Integer(Regexp.last_match(1)) * m[Regexp.last_match(2)]
rescue
  raise StandardError, "invalid byte size: #{s.inspect}"
end

cli = OpenSearch::CLI.new do |opts|
  opts.banner = "Usage: #{$PROGRAM_NAME} [options] [indices]"

  opts.separator ""
  opts.separator "Indices scope options:"

  opts.on("--[no-]periodic", "Only consider periodic indices") do |periodic|
    options[:periodic] = periodic
  end

  opts.separator ""
  opts.separator "Logging options:"

  opts.on("--log-level=LEVEL", [:debug, :info, :warn, :error, :fatal], "Set the log level for the output") do |level|
    options[:logger].level = level
  end

  opts.separator ""
  opts.separator "Shard size options:"

  opts.on("-p", "--profile=PROFILE", [:read, :write], "Select a workload profile (read, write)") do |profile|
    if profile == :read
      options[:min_shard_size] = 10.gigabytes
      options[:max_shard_size] = 30.gigabytes
    elsif profile == :write
      options[:min_shard_size] = 30.gigabytes
      options[:max_shard_size] = 50.gigabytes
    end
  end

  opts.on("--min-shard-size=SIZE", "Set the minimum size of shards") do |size|
    options[:min_shard_size] = parse_bytes(size)
  end

  opts.on("--max-shard-size=SIZE", "Set the maximum size of shards") do |size|
    options[:max_shard_size] = parse_bytes(size)
  end
end

cli.load
cli.parse!

if options[:max_shard_size] < options[:min_shard_size]
  logger.fatal("Maximum shard size (#{options[:max_shard_size]}) is less than minimum shard size (#{options[:min_shard_size]})")
  exit 1
end

index_param = ARGV.first || "_all"

index_list = OpenSearch::Audit::IndexList.new

cli.client.cat.indices(index: index_param, format: "json", bytes: "b", s: "index").map do |index_data|
  index = OpenSearch::Audit::Index.new(index_data)
  next if options[:periodic] && !index.periodic?

  index_list.add(index)
end

puts "Found index groups:"
index_list.group_names.each do |group_name|
  group_indices = OpenSearch::Audit::IndexGroup.new(index_list.where(group_name: group_name))

  trends = [14, 7].map do |n|
    format("%<trend>9s (last %<n>d)",
      trend: ActiveSupport::NumberHelper.number_to_human_size(group_indices.median_shard_size_trend(n)),
      n: n)
  end.join(", ")
  puts format("%<count>4d x %<name>-#{index_list.longest_index_name}s %<median_primary_size>9s [primary shards: %<primary_shard_count>2d, min: %<min>9s max: %<max>9s, med: %<med>9s, trends: %<trends>s]\n",
    count: group_indices.count,
    name: group_name,
    median_primary_size: ActiveSupport::NumberHelper.number_to_human_size(group_indices.median_primary_size),
    primary_shard_count: group_indices.median_primary_shard_count,
    min: ActiveSupport::NumberHelper.number_to_human_size(group_indices.min_shard_size),
    max: ActiveSupport::NumberHelper.number_to_human_size(group_indices.max_shard_size),
    med: ActiveSupport::NumberHelper.number_to_human_size(group_indices.median_shard_size),
    trends: trends)
end

checker = OpenSearch::Audit::Checks::ShardSize.new(index_list, options)
checker.check

checker = OpenSearch::Audit::Checks::IndexName.new(index_list, options)
checker.check

mappings = cli.client.indices.get_mapping(index: index_param)
mappings.each do |index, mapping|
  index_list.find_by(name: index).enrich(:mapping, mapping)
end

checker = OpenSearch::Audit::Checks::DynamicMapping.new(index_list, options)
checker.check

checker = OpenSearch::Audit::Checks::Conflicts.new(index_list, options)
checker.check

checker = OpenSearch::Audit::Checks::DoubleKeyword.new(index_list, options)
checker.check

checker = OpenSearch::Audit::Checks::UnexpectedType.new(index_list, options)
checker.check
